org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

version=2.2.0
group=com.vnap

fabric_api_version=0.160.6+26.3
emf_version=3.3.6-fabric-26.3
etf_version=7.2.2-fabric-26.3
modmenu_version=21.0.0-beta.1
