org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.15-SNAPSHOT

version=2.1.0
group=com.vnap

fabric_api_version=0.155.3+26.1.2
emf_version=3.2.4-fabric-26.1
etf_version=7.1-fabric-26.1
modmenu_version=18.0.1
